In [1]:
import pandas as pd
import os
import shutil

In [2]:
test_ds = pd.read_csv('Images/traffic-signs/Test.csv')
test_ds.head()

   Width  Height  Roi.X1  Roi.Y1  Roi.X2  Roi.Y2  ClassId            Path
0     53      54       6       5      48      49       16  Test/00000.png
1     42      45       5       5      36      40        1  Test/00001.png
2     48      52       6       6      43      47       38  Test/00002.png
3     27      29       5       5      22      24       33  Test/00003.png
4     60      57       5       5      55      52       11  Test/00004.png

In [12]:
for i in range(43):
    directory = f'Images/traffic-signs/Test/{i}'
    if not os.path.exists(directory):
        os.makedirs(directory)

In [52]:
amount_images = test_ds['Path'].count()
image_path = ""

for i in range(amount_images):
    image_path = f"Images/traffic-signs/{test_ds['Path'][i]}"
    if os.path.exists(image_path):
        target_path = f"Images/traffic-signs/Test/{test_ds['ClassId'][i]}"
        shutil.move(image_path, target_path)
#         print(image_path)
#         print(target_path)
#     break;

In [55]:
test_ds[test_ds['ClassId'] == 0].head()

     Width  Height  Roi.X1  Roi.Y1  Roi.X2  Roi.Y2  ClassId            Path
243     39      39       6       5      34      34        0  Test/00243.png
252     51      52       6       6      46      47        0  Test/00252.png
403     43      44       5       5      38      39        0  Test/00403.png
579     37      37       6       6      32      32        0  Test/00579.png
675     45      47       5       5      40      42        0  Test/00675.png